/**
 * cryptodashboard_backend
 * cryptodashboard
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mozzonfederico@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuotationWithRelations } from './quotationWithRelations';


/**
 * (tsType: CoinWithRelations, schemaOptions: { includeRelations: true })
 */
export interface CoinWithRelations { 
    nameCoin: string;
    idCoin?: string;
    acronym: string;
    descriptionCoin: string;
    linkToWikipedia: string;
    quotations?: Array<QuotationWithRelations>;
}

