/**
 * backend
 * iaw
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mozzonfederico@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuotationWithRelations } from './quotationWithRelations';
import { ExchangeWithRelations } from './exchangeWithRelations';


/**
 * (tsType: CoinWithRelations, schemaOptions: { includeRelations: true })
 */
export interface CoinWithRelations { 
    idCoin?: string;
    nameCoin: string;
    description: string;
    acronym: string;
    linkToWikipedia: string;
    exchanges?: Array<ExchangeWithRelations>;
    quotations?: Array<QuotationWithRelations>;
}

