/**
 * backend
 * iaw
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mozzonfederico@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoinScopeFilter { 
    offset?: number;
    limit?: number;
    skip?: number;
    order?: string | Array<string> | null;
    where?: { [key: string]: object; };
    fields?: any | Set<string> | null;
    include?: Array<{ [key: string]: object; }>;
}

