/**
 * cryptodashboard_backend
 * cryptodashboard
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mozzonfederico@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Coin, \'idCoin\'>, schemaOptions: { title: \'NewCoin\', exclude: [ \'idCoin\' ] })
 */
export interface NewCoin { 
    nameCoin: string;
    acronym: string;
    descriptionCoin: string;
    linkToWikipedia: string;
}

