/**
 * backend
 * iaw
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mozzonfederico@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<Quotation, \'idQuotation\'>, \'coinId\'>, schemaOptions: { title: \'NewQuotationInCoin\', exclude: [ \'idQuotation\' ], optional: [ \'coinId\' ] })
 */
export interface NewQuotationInCoin { 
    price: number;
    dateCreation: string;
    result: boolean;
    coinId?: string;
    exchangeName?: string;
}

