/**
 * cryptodashboard_backend
 * cryptodashboard
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mozzonfederico@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Partial<Quotation>, schemaOptions: { partial: true })
 */
export interface QuotationPartial { 
    idQuotation?: number;
    priceQuotation?: number;
    exchangeQuotation?: string;
    coinId?: number;
}

