/**
 * backend
 * iaw
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mozzonfederico@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Partial<Quotation>, schemaOptions: { partial: true })
 */
export interface QuotationPartial { 
    price?: number;
    idQuotation?: string;
    dateCreation?: string;
    result?: boolean;
    coinId?: string;
    exchangeName?: string;
}

