export * from './coinController.service';
import { CoinControllerService } from './coinController.service';
export * from './coinExchangeController.service';
import { CoinExchangeControllerService } from './coinExchangeController.service';
export * from './coinQuotationController.service';
import { CoinQuotationControllerService } from './coinQuotationController.service';
export * from './exchangeController.service';
import { ExchangeControllerService } from './exchangeController.service';
export * from './loginController.service';
import { LoginControllerService } from './loginController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export * from './quotationController.service';
import { QuotationControllerService } from './quotationController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [CoinControllerService, CoinExchangeControllerService, CoinQuotationControllerService, ExchangeControllerService, LoginControllerService, PingControllerService, QuotationControllerService, UserControllerService];
